name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.8'  # Określa wersję Pythona, np. '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Instalacja zależności z pliku requirements.txt

      - name: Run tests
        run: |
          pytest  # Uruchamianie testów za pomocą pytest
